#expenses= [6.50,4.30,]
#total=0
#for expense in expenses:
 #   total = total + expense
#  print(f"Current expense: {expense}")
 #   print(f"All expenses: {expenses}")
    
  #  print(f"Total expenses: ${total}")
import time
print('hi')
time.sleep(.5)
print('hi')
time.sleep(.5)
print('hi')
time.sleep(.5)
print('hi')
time.sleep(.5)
print('hi')
time.sleep(.5)
print('hi')
time.sleep(.5)
print('hi')
time.sleep(.5)
print('hi')
time.sleep(.5)
print('hi')
time.sleep(.5)
print('hi')
time.sleep(.5)
print('hi')
time.sleep(.5)
print('hi')
time.sleep(.5)
print('hi')
time.sleep(.5)
print('hi')
time.sleep(.5)
print('hi')
time.sleep(.5)